### ISSUE TITLE
Remove command line tool dependency

### ISSUE THREAD

**Issue by wdhongtw** [wdhongtw/vscode-gpg-indicator#14]
> Current implementation require a pty between this extension and GPG tools to send passphrase, so we use expect to handle this. I wish I can remove this dependency in the future.

Extension may connect to GPG agent through the socket and communecate using the agent protocol.
Within the session, trigger the sign hash command and provide the passphrase.

See: <https://www.gnupg.org/documentation/manuals/gnupg/Agent-Protocol.html#Agent-Protocol>

**Comment by sonithls** [comment]
Expect tool is not working in the flatpack version of VS Code. When a passphrase is entered, there is an error message: "Failed to unlock: can not find the expect tool". This issue is not seen in the installation from Microsoft yum repo.

**Comment by wdhongtw** [comment]
Hi @sonithls

I'm working one alternative solution for the `expect` tool, but the solution still relies on unix socket, which is restricted on [flatpack's sandbox feature](https://docs.flatpak.org/fr/latest/sandbox-permissions-reference.html).

Even with the alternative solution, I'm afaid that there is only small chance for GPG operation to work in sandbox environment. :(

**Comment by wdhongtw** [comment]
fixed in #27
