### ISSUE TITLE
Support untrusted workspace

### ISSUE THREAD

**Issue by wdhongtw** [wdhongtw/vscode-gpg-indicator#17]
We can support the new VS Code security feature - untrusted workspace directly,
since this extension do not depend on any part of the untrusted code base.

There since no document page about this. Currently it's only mentioned in VS Code release notes:
<https://code.visualstudio.com/updates/v1_56>

> You can declare your extension to provide complete or partial or no support in untrusted workspaces using the `untrustedWorkspaces` capability in `package.json`.

```json
"capabilities": {
  "untrustedWorkspaces": {
    "supported": true
  }
}
```

**Comment by AnnAngela** [comment]
I will take a look at it tomorrow.
