### ISSUE TITLE
Consider publishing to Open VSX

### ISSUE THREAD

**Issue by ajhalili2006** [wdhongtw/vscode-gpg-indicator#24]
## About This Issue

Because of Microsoft's strict policies regarding the use of extensions in the VS Code Marketplace, most of non-Microsoft distributions, including [code-server (through some configuration magic on end-user)](https://github.com/cdr/code-server)and [even Gitpod](https://github.com/gitpod-io/openvscode-server) use Open VSX instead.

## Alternative Options

While there's an option to download the extension as a VSIX file and the upload it to my instance of a non-Microsoft distribution of VS Code, the problem here is we're approaching the gray area of Microsoft's EULA on VS Code.

**Comment by wdhongtw** [comment]
I didn't aware that there are some platforms other than VS Code Marketplace before. I'll take a look at this part these days. :D

**Comment by barandasdemir** [comment]
I second this. [VSCodium](https://github.com/VSCodium/vscodium) uses Open VSX by default as well.

**Comment by TobiaszCudnik** [comment]
code-server changed to open vsx by default starting from v4.

Not sure why one have to sign the eclipse publisher agreement for MIT extensions thought?

**Comment by ajhalili2006** [comment]
> code-server changed to open vsx by default starting from v4.
> 
> Not sure why one have to sign the eclipse publisher agreement for MIT extensions thought?

@TobiaszCudnik Maybe for conpilance reasons probably.

Also since the last update, I'll check if the community submitted the repo for autopublishing under an OpenVSX-managed bot soon.

**Comment by wdhongtw** [comment]
Done. :D

See: <https://open-vsx.org/extension/wdhongtw/gpg-indicator>
