### ISSUE TITLE
Logging sensitive information

### ISSUE THREAD

**Issue by qm3ster** [wdhongtw/vscode-gpg-indicator#29]
If I had to guess, the fact that the following is visible in VSCode "OUTPUT" tab for "GPG Indicator" is a security issue, even beyond the fact that it can be seen there.
```
Assuan data receive: INQUIRE PASSPHRASE
Assuan data send: D  literally_my_actual_passphrase_in_plain_text
Assuan data send: END
Assuan data receive: D (9:sig-val(2:rsa(7:s512:d"��f2��S��������������������������������������������������������������������������������������������Assuan data receive: OK
Assuan data send: BYE
```
Concerning is both the passphrase, and the binary dump that follows, considering that if it is logged to a file it will be recoverable in full, unlike the mostly-secure replacement characters seen on-screen.
If I understand correctly, that includes the full decrypted key?
Is there any reason the extension should even receive that?

**Comment by wdhongtw** [comment]
Maybe I should refactor the extension library to support multi-level logging, and add a option for user to adjust the desired log level (of which the default value won't include Assuan operation log).

**Comment by qm3ster** [comment]
Yes, is the private key (decrypted with the passphrase) logged there?
(regardless, the fact the passphrase gets printed is probably bad enough to change this)
