### ISSUE TITLE
Can not found key on Windows

### ISSUE THREAD

**Issue by L-Sun** [wdhongtw/vscode-gpg-indicator#32]
The extension can not get the gpg key on Windows. The debug output is following:
```
Active GPG Indicator extension ...
Setting: sync status interval: 30
Create key status manager
Update folder information
Change folder to /e:/workspace/cpp/HitagiEngine
Got one update function
Can not found key for folder: /e:/workspace/cpp/HitagiEngine
```

Note that there is a slash `/` at the beginning of the workspace path. When using this format, the function `exec` may throw an exception because `URI.path` is not a valid file path format on Windows.
A solution might be to change `uri.path` to `uri.fsPath`.

```
uri.paht   --->  /e:/workspace/cpp/HitagiEngine
uri.fsPath --->  e:\\workspace\\cpp\\HitagiEngine
```

https://github.com/wdhongtw/vscode-gpg-indicator/blob/b051dd8c32da4a81fc6315dba6fe3126bcdb1ae5/src/extension.ts#L15-L17

https://github.com/wdhongtw/vscode-gpg-indicator/blob/b051dd8c32da4a81fc6315dba6fe3126bcdb1ae5/src/indicator/git.ts#L28-L33

**Comment by wdhongtw** [comment]
Hi @L-Sun, although it only requires one line modification, feel free to submit MR if you want some credit. :D

I guess I'll release new version next weekend.
