### ISSUE TITLE
Add option to hook into commit and promt for password

### ISSUE THREAD

**Issue by Manokii** [wdhongtw/vscode-gpg-indicator#39]
This would be really helpful especially for people like me who'd like for my sessions to expire in short amount of time

**Comment by wdhongtw** [comment]
The passphrase is always kept in memory by `gpg-agent` for some period. Not by VS Code or this extension. (Althought this extension can also keep the passphrase, technically). See `default-cache-ttl` and `max-cache-ttl` option from `gpg-agent` for more details. :D

To my knownledge, there is no extension API for an extension to do anything around the git operation. And it's hard for extension to implement it correctly across different environments. I thought the API may be there someday. But when that day comes, the core develop team of VS Code should also solve this usecase already...

See this thread if you are interested :D
- <https://github.com/microsoft/vscode/issues/43809>
