### ISSUE TITLE
Read global Git config 

### ISSUE THREAD

**Issue by kitos9112** [wdhongtw/vscode-gpg-indicator#4]
Hello,

I've just arrived at your Git repo due to the existing limitation of natively unlock a [GPG key from VScode](https://github.com/microsoft/vscode/issues/43809)

After installing expect on my local Ubuntu WSL2 distribution and configure my local `.git/config` everything seemed to work quite well. Albeit, in the beginning, I was expecting this extension to also read the `global` Git configuration file at the home directory if the 2 required settings do not exist In the local file. This would be fantastic as I normally just configure my default `.gitconfig` at `~/.gitconfig` and do not often rely on local git configs.

Thanks,

**Comment by wdhongtw** [comment]
Hi @kitos9112 

Usually I only use local config for signing related settings, and that's the reason for the current implement and limitation.
But, as you mentioned, it would be fantastic to support global config.

What we only need is removing the `--local` option from the `git` command, and everything should be fine.
Would you like to give some contribution? :D

**Comment by kitos9112** [comment]
Hi @wdhongtw 

That's fair 👍🏼 - Not a Javascript guy I got to say but I'll give it a go today.

Cheers!
