### ISSUE TITLE
Use 1Password to get Key password instead of prompt

### ISSUE THREAD

**Issue by muuvmuuv** [wdhongtw/vscode-gpg-indicator#41]
Since 1Password 8, they have a CLI and integrations. Would be wonderfull if we could bind a key with an 1Password entry and it hooks into 1Password to retrieve the password. Like they do with SSH logins.

My current process looks like this:

1. opens project
2. gpg not unlocked
3. CMD + SHIFT + X (opens 1Password dialog)
4. search GPG
5. Copy password
6. CMD + SHIFT + P
7. search gpg
8. Unlock with pw

Would be:

1. opens project
2. gpg not unlocked
3. 1Password prompts for confirmation from gpg extension or if 1P already unlocked nothing

**Comment by muuvmuuv** [comment]
There is also a typed JS SDK from 1Password itself: https://www.npmjs.com/package/@1password/op-js

**Comment by muuvmuuv** [comment]
Got it working here: https://github.com/muuvmuuv/1password-get-gpg/blob/main/main.js

**Comment by muuvmuuv** [comment]
Ok, for anyone coming here, you probably don't need this. 1Password has built-in support for SSH-key commit singing: https://developer.1password.com/docs/ssh/git-commit-signing

**Comment by AlexanderAllen** [comment]
If 1Password has support for the workflow that you need, would it be OK to close the issue, then?

**Comment by muuvmuuv** [comment]
Yes
