### ISSUE TITLE
Support `subkey!` format

### ISSUE THREAD

**Issue by LHLaurini** [wdhongtw/vscode-gpg-indicator#42]
When `.gitconfig` contains a subkey in the "`subkey!`" format
```
[user]
        signingKey = 0123456789ABCDEF0123456789ABCDEF01234567!
```
the extension reports
> `[WARN] Can not found key for folder`

Removing the exclamation mark is enough to make it work. For me that's not a problem, since I have a single private signing subkey on my machine. However, it might be an issue for users with multiple subkeys.

I believe this can be solved by simply accepting and ignoring the trailing exclamation mark.

**Comment by wdhongtw** [comment]
@LHLaurini 
Thanks for creating this issue, I didn't notice this use case before. :D
