### ISSUE TITLE
Provide meaningful error message when 'expect' is not installed

### ISSUE THREAD

**Issue by fcastilloec** [wdhongtw/vscode-gpg-indicator#6]
It seems that there isn't any meaningful message that instructs the user when they don't have `expect` installed.
The extension should test (i.e. `command -v expect`) if the requirements are met, if not it should instruct the user to install the required package.

I initially made sure to have `expect` installed but when I ssh into a remote machine (using vscode remote), the extension got transferred and I forgot to check if `expect` was available on the remote machine. I encountered a cryptic message: `Failed to unlock: write EPIPE`, which made me think that there was some problem with GPG or the fact that it was running through SSH, finally realizing it was unmet requirements of the extension.

I'm not familiar with vscode extension, but it seems easy to implement this check. You already have the `textSpawn` function that can be used and it can be check when activating the extension, or right before unlocking the key.

**Comment by wdhongtw** [comment]
It's sounds good to add this check. I think I will work with this recently. :D

**Comment by wdhongtw** [comment]
The existence check of `expect` tool is added in version 0.3.3, and the new version is published now.

Since the instruct action require new UI flow, it's not included in this version.
We may add this in future release, but now I only provides meaningful error message. :D
